export type SonoramaStatus='Idle'|'Analyzing'|'Reviewing'|'Waiting for input'|'Blocked';
export type Operation='analyze_song'|'create_visual_thesis'|'create_visual_bible'|'create_camera_language'|'create_color_language'|'create_editing_language'|'review_storyboard'|'review_shot'|'compare_looks'|'detect_visual_repetition'|'detect_continuity_risk'|'propose_visual_motif'|'propose_symbolic_language'|'remember_creative_decision'|'summarize_project_direction'|'review_final_sequence'|'create_creative_brief';
export interface ProjectScope {org_id:string;project_id:string;creator_id:string}
export interface FeatureFlags {sonorama_operational:boolean;sonorama_creative_memory:boolean;sonorama_creative_qa:boolean;sonorama_lookdev:boolean;sonorama_creative_pulse:boolean}
export interface MetricPoint {time:number;value:number;unit:string}
export interface AudioMetrics {bpm?:number;sections?:Array<{id:string;label:string;start:number;end:number;confidence?:number}>;energy?:MetricPoint[];loudness_contour?:MetricPoint[];spectral_tendencies?:{centroid_hz:number;bands?:number[]};dynamics?:{crest_db?:number;range_db?:number;width_ratio?:number;rms_dbfs?:number};structural_markers?:Array<{time:number;label:string}>;lyrics?:string;transcript?:string;user_notes?:string;provenance?:{source:string;analysis_id?:string;scope:string;measured_at?:string;limitations:string[]}}
export interface CreativeBrief {core_emotion:string;visual_metaphor:string;camera_language:string;color_arc:string;editing_rhythm:string;motifs:string;do_not:string;hero_moments:string}
export interface VisualThesis {core_emotion:string;emotional_arc:string;central_metaphor:string;visual_world:string;palette:string;lighting_direction:string;camera_language:string;rhythm_editing:string;character_presence:string;spatial_logic:string;recurring_motifs:string;symbolic_vocabulary:string;anti_cliche_notes:string;forbidden_directions:string;hero_moments:string;continuity_risks:string}
export interface VisualBible {palette:string;lighting_rules:string;lens_camera_rules:string;framing_grammar:string;environment_rules:string;character_presentation:string;costume_language:string;texture:string;contrast:string;motion_style:string;montage_rhythm:string;forbidden_elements:string;visual_motif_library:string;continuity_constraints:string}
export interface CreativeQAResult {verdict:'APPROVE'|'APPROVE WITH NOTES'|'REVISE';evidence_mode:'storyboard_text'|'frame_observed'|'sequence_observed'|'shot_metadata';dimensions:Array<{name:string;status:'pass'|'note'|'revise'|'not_evaluated';reason:string;evidence_refs:string[];suggestion:string}>;limitations:string[]}
export interface CreativeDecision {choice:string;decision:'approved'|'rejected';reason:string;category:'camera'|'color'|'motif'|'continuity'|'taboo'|'look'|'direction';subject_ref:string;taste_code?:string}
export interface LookdevComparison {looks:Array<{id:string;mood:string;novelty:string;coherence:string;character_fit:string;project_fit:string;continuity:string;visual_potential:string;evidence_ref:string}>;recommendation:string;reasons:string[];requires_human_approval:true}
export interface CreativeArtifact<T> extends ProjectScope {schema_version:2;kind:string;revision:number;source_hash:string;author:'human'|'sonorama'|'deterministic';previous_id:string|null;payload:T;approval:'draft';content_hash:string}
export interface AudioVisualInterpretation {observations:string[];suggestions:string[];limitations:string[]}
